# Generated by Django 2.2.1 on 2019-05-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='博客名')),
                ('abstract', models.TextField(verbose_name='摘要')),
                ('content', models.TextField(verbose_name='博客内容')),
                ('read_num', models.IntegerField(verbose_name='阅读数')),
                ('comment_num', models.IntegerField(verbose_name='评论数')),
                ('image', models.FileField(upload_to='static/user_data/blog_img', verbose_name='博客图片')),
                ('time', models.DateField(auto_now_add=True, verbose_name='发布日期')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='标签名')),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='用户名')),
                ('avatar', models.CharField(max_length=128, verbose_name='头像')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('time', models.DateField(auto_now_add=True, verbose_name='评论日期')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='文章id')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='gategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='文章分类'),
        ),
    ]
